DROP SEQUENCE MVCBOARDSEQ
DROP TAVBLE MVCBOARD

CREATE SEQUENCE MVCBOARDSEQ
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
)

INSERT INTO MVCBOARD
VALUES(MVCBOARDSEQ.NEXTVAL, '관리자', 'TEST 글 입니다', 'TEST1234', SYSDATE);

INSERT INTO MVCBOARD
VALUES(MVCBOARDSEQ.NEXTVAL, 'JAVA', 'SERVLET 어렵다', '아직 JSP인데?', SYSDATE);


SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE
FROM MVCBOARD
ORDER BY SEQ DESC;