DROP TABLE CALBOARD;
DROP SEQUENCE CALBOARDSEQ;

CREATE SEQUENCE CALBOARDSEQ;

-- MDATE : 일정날짜(년월일시분) 내가 일정을 추가한 날짜
CREATE TABLE CALBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL,
	REGDATE DATE NOT NULL
);


SELECT SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
FROM CALBOARD
WHERE MDATE LIKE '20200724%'
AND ID = 'kh';

INSERT INTO CALBOARD